### ISSUE TITLE
Seek help

### ISSUE THREAD

**Issue by GTwhy** [adamgallas/MIT_6.175_LAB#1]
Hi, glad to see this repo!

I'm learning this lab too, and I can not find the init lab code of [fall 2017 version](http://csg.csail.mit.edu/6.175/labs.html).

Is the code in this repo [2016 version](http://csg.csail.mit.edu/6.175/archive/2016/labs.html)? Do you know how to get the 2017 version?

Thanks!

**Comment by GTwhy** [comment]
Oh, I found [this](https://github.com/fabatef/6.175), and it seems like 2017 version.

**Comment by adamgallas** [comment]
Hi
This is the 2017 version. I couldn't find the initial lab code of fall 2017 version either. I manually merged several versions of this MIT lab codes from other repos.
I discovered fabatef's repo too when I tried to find solutions of the RISCV labs.

**Comment by GTwhy** [comment]
I found [Multipliers.bsv](https://github.com/adamgallas/MIT_6.175_LAB/blob/main/6.175-lab2/Multipliers.bsv) in the lab2 of this repo, which is included in lab3 in 2017 version. So I thought it is the 2016 version, but it doesn't matter.

Thanks for your reply. Wish you a happy life in Yanqi Lake Campus of UCAS : )

**Comment by adamgallas** [comment]
thank you! wish you a fruitful experience in Datenlord!
